server:
  port: 8080

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.19.53.15:1521:pgtstdb
    username: pangea2test
    password: pangea2test#

mybatis-plus:
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.example.demo.mapper: debug